# Generated by Django 4.0.5 on 2022-06-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Idproducto'),
        ),
    ]
