# Generated by Django 4.0.5 on 2022-06-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_precio_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria2',
            fields=[
                ('idCategoria2', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria2', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Idcliente')),
                ('nombre2', models.CharField(max_length=50, verbose_name='Nombre2')),
                ('edad', models.CharField(max_length=20, verbose_name='Edad')),
                ('categoria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria2', verbose_name='Categoria2')),
            ],
        ),
    ]
